name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release with GoReleaser
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.3'

      - name: Install GoReleaser
        run: |
          curl -sSfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh

          - name: Install GitVersion
          uses: gittools/actions/gitversion/setup@v0.9.7
          with:
            versionSpec: '5.x'
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Display SemVer
        run: |
          echo "SemVer: $GITVERSION_SEMVER" && echo "$version" && echo "$major.$minor.$patch"
      - name: Create git tag
        run: |
          git tag $GITVERSION_SEMVER
      - name: Push git tag
        run: git push origin $GITVERSION_SEMVER
      - name: Run GoReleaser
        run: goreleaser release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
